<?php

/**
 * @file
 * Contains tetranz_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tetranz_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tetranz_test module.
    case 'help.page.tetranz_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tetranz_test_theme() {
//  return [
//    'tetranz_test' => [
//      'render element' => 'children',
//    ],
//  ];
  return [
    'tetranz_test' => [
      'variables' => [
        'name' => NULL, 
      ],
    ],
  ];
}
